[project]
name = "pyingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mypy>=2.4.0",
    "pre-commit>=4.6.2",
    "pydantic>=2.13.5",
    "ruff>=0.16.10",
]

[project.scripts]
pyingest = "pyingest:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=2.4.0",
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.ruff]
line-length=88

[tool.ruff.lint]
select = ["E", "F", "I"]  # Error, Pyflakes, ISort

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
python_version = "3.14"
strict = true
warn_return_any = true
warn_unused_configs = true
mypy_path = "src"
explicit_package_bases=true
plugins=["pydantic.mypy"]
